config/routes.rb
Rails.application.routes.draw do
	root 'catalogs#index'
 	
	get '/signup', to: 'users#new', as: 'signup'
	get '/signin', to: 'sessions#new', as: 'signin'
	post '/signin', to: 'sessions#create'
	get '/signout', to: 'sessions#destroy', as: 'signout'
	get 'reset_password', to: 'password_resets#new'
	get '/expired_token', to:'password_resets#expired_token'

	namespace :admin do
		get 'base/index'
		resources :authors
		resources :books
		resources :publishers
	end
	
	resources :users, only: [:index,:show, :new, :create, :destroy]
	resources :catalogs, only: [:index, :show] do
		collection do
			post :search, to: "catalogs#search"
		end
	end

	resources :carts,only: [:show, :destroy]
	resources :cart_items, only: [:create]
	resources :orders, only: [:new, :create]
	resources :password_resets, only: [:create,:edit,:update]
	

end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :publisher
	has_many :publications, dependent: :destroy
	has_many :authors, through: :publications

	validates :title, presence: true
	validates :isbn, presence: true
	validates :description, presence: true
	validates :published_at, presence: true
	validates :publisher_id, presence: true
	validates :page_count, numericality: {only_integer: true, greater_than: 0}
	validates :price, numericality: {greater_than_or_equal_to: 0.0}

	scope :recent, lambda {order("books.created_at DESC")}

	mount_uploader :book_cover, BookCoverUploader

	def self.search_by_title(title)
		where('title LIKE ?', "%#{title}%").order(:title)
	end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
  before_action :require_signin
  before_action :require_admin
 before_action :find_books, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.recent
  end

  def show
  end

  def new
    @book = Book.new
    @publishers = Publisher.all
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "Book has been created"
      redirect_to [:admin, @book]
    else
      flash[:danger] = "Book has not been created"
      @publishers = Publisher.all
      @authors = Author.all
      render :new
    end
  end

  def edit
    @publishers = Publisher.all
    @authors = Author.all
  end

  def update
    if @book.update(book_params)
      flash[:success] = "Book has been updated"
      redirect_to [:admin, @book]
    else
      flash[:danger] = "Book has not been updated"
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:success] = "Book has been deleted"
    redirect_to admin_books_path
  end

  private

    def find_books
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:book_cover,:title, :isbn, :description, :published_at, :publisher_id, :page_count, :price,author_ids: [])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :find_books, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.recent
  end

  def show
  end

  def new
    @book = Book.new
    @publishers = Publisher.all
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "Book has been created"
      redirect_to @book
    else
      flash[:danger] = "Book has not been created"
      @publishers = Publisher.all
      @authors = Author.all
      render :new
    end
  end

  def edit
    @publishers = Publisher.all
    @authors = Author.all
  end

  def update
    if @book.update(book_params)
      flash[:success] = "Book has been updated"
      redirect_to @book
    else
      flash[:danger] = "Book has not been updated"
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:success] = "Book has been deleted"
    redirect_to books_path
  end

  private

    def find_books
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:book_cover,:title, :isbn, :description, :published_at, :publisher_id, :page_count, :price,author_ids: [])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/_form.html.erb
<div class="col-md-6 col-md-offset-3" style="text-align:center">
<%=bootstrap_form_for([:admin, @book], :html=> {class: 'form-horizontal'}) do |f| %>
	
	<div class="form-group">
		<%=f.text_field :title, hide_label: true, placeholder: "enter Title (ex: Java Book)", id: "bookTitle", class: "form-control"%>
	</div>

	<div class="form-group">
		<%=f.text_field :isbn, hide_label: true, placeholder: "enter ISBN (ONLY 13 DIGITS)", id: "bookIsbn", class: "form-control"%>
	</div>

	<div class="form-group row" >
		
		<%=f.number_field :page_count, hide_label: true, placeholder: "enter Page Count (ex: 584)", id: "bookPage_count", class: "form-control"%>
		
		<%=f.text_field :price, hide_label: true, placeholder: "enter Price (ex: 38.88)", id: "bookPrice", class: "form-control"%>
		
	</div>

	<div class="form-group">
		<%=f.text_area :description, hide_label: true, placeholder: "enter description (not more than 500 characters)", id: "bookDescription", class: "form-control"%>
	</div>

	<div class="form-group">
		<%=f.date_field :published_at, hide_label: true, id: "bookPublished_at", class: "form-control"%>
	</div>

	<div class="form-group">
		<%=f.select :publisher_id, @publishers.map{|publisher| [publisher.name, publisher.id]}, prompt: "Select Publisher", class: "form-control"%>
	</div>

	<div class="form-group">
		<%#=f.select :author_ids, @authors.all.map{|author| [author.id, author.full_name]},class: "form-control",id: "chosen_select", include_blank: true%>
		<%= f.collection_select :author_ids, @authors, :id, :full_name, {}, { class: "form-control",id: 'chosen_select', multiple: true } %>
	</div>

	<div class="form-group">
		<%=f.file_field :book_cover, placeholder: "Uplaod Boook Cover",class: "form-control", id: "book_cover"%>
	</div>

	<div class="form-group actions control-group">
		<%=f.submit class: "btn btn-info"%>
	</div>
<%end%>
<br/><br/>
</div>

<%=javascript_tag do%>
	$('#bookIsbn').on("input", function(e){
		var a = $('#bookIsbn').val();
		if(a.length==13){
			$('#bookIsbn').css({"border-color":"#64b898","border-style":"solid","border-width":"5px"});
		}
		else{$('#bookIsbn').css({"border-color":"#ff6666","border-style":"solid","border-width":"5px"});}

		if(a.length>13){alert("only 13 character permitted");
		$('#bookIsbn').val(a.substring(0,13));}

	});
	

<%end%>
<!--style type="text/css">#chosen_select{width:650px !important;}</style-->

app/views/admin/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/admin/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/admin/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/admin/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>
<%=link_to "Add New Book", new_admin_book_path%>

app/views/admin/books/new.html.erb
<div class="row" style="width:100vw">
  <div class="heading" style="text-align:center;">
      <h2 style="letter-spacing:7px;line-height: 1.6em;">Add a New Book <span class="glyphicon glyphicon-book"></span></h2>
  </div>
</div>

<div class="row" style="width:100vw">
  <%=render "form"%>
</div>

app/views/admin/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/admin/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>