config/routes.rb
Rails.application.routes.draw do
	root 'catalogs#index'
 	
	get '/signup', to: 'users#new', as: 'signup'
	get '/signin', to: 'sessions#new', as: 'signin'
	post '/signin', to: 'sessions#create'
	get '/signout', to: 'sessions#destroy', as: 'signout'
	get 'reset_password', to: 'password_resets#new'
	get '/expired_token', to:'password_resets#expired_token'

	namespace :admin do
		get 'base/index'
		resources :authors
		resources :books
		resources :publishers
	end
	
	resources :users, only: [:index,:show, :new, :create, :destroy]
	resources :catalogs, only: [:index, :show] do
		collection do
			post :search, to: "catalogs#search"
		end
	end

	resources :carts,only: [:show, :destroy]
	resources :cart_items, only: [:create]
	resources :orders, only: [:new, :create]
	resources :password_resets, only: [:create,:edit,:update]
	

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :publications, dependent: :destroy
	has_many :books, through: :publications

  validates :first_name, presence: true
  validates :second_name, presence: true

  def full_name
    "#{first_name} #{second_name}"
  end

  scope :recent, lambda {order("authors.created_at DESC")}
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < Admin::BaseController
  before_action :require_signin
  before_action :require_admin
  before_action :find_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.recent
  end

  def show
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = "Author has been successfully created"
      redirect_to [:admin, @author]
    else
      flash[:danger] = "Author has not been created"
      render :new
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      flash[:success] = "Author has been successfuly Updated"
      redirect_to [:admin, @author]
    else
      flash[:danger] = "Author has not been Updated"
      render :edit
    end
  end

  def destroy
    @author.destroy
    flash[:success] = "Author has been successfuly Deleted"
    redirect_to admin_authors_path
  end

  private

    def find_author
      @author = Author.find(params[:id])
    end

    def author_params
      params.require(:author).permit(:first_name, :second_name)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :require_signin
  before_action :require_admin
  before_action :find_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.recent
  end

  def show
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = "Author has been successfully created"
      redirect_to @author
    else
      flash[:danger] = "Author has not been created"
      render :new
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      flash[:success] = "Author has been successfuly Updated"
      redirect_to @author
    else
      flash[:danger] = "Author has not been Updated"
      render :edit
    end
  end

  def destroy
    @author.destroy
    flash[:success] = "Author has been successfuly Deleted"
    redirect_to authors_path
  end

  private

    def find_author
      @author = Author.find(params[:id])
    end

    def author_params
      params.require(:author).permit(:first_name, :second_name)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/admin/authors/_form.html.erb
<div class="col-md-6 col-md-offset-3" style="text-align:center">
<%=bootstrap_form_for([:admin, @author], :html=> {class: 'form-horizontal'}) do |f| %>
<div class="form-group">
  <%= f.text_field :first_name, class: "form-control",hide_label: true,id: "firstName", placeholder: "enter First Name (ex: Bill)" %>
</div>
<div class="form-group">
  <%= f.text_field :second_name, class: "form-control",hide_label: true,id: "secondName", placeholder: "enter Last Name (ex: Gates)"%>
</div>

<br />

<div class="form-group actions control-group">
  <%if @t == 1%>
    <%=f.submit class: "btn btn-primary"%>
  <%else%>
    <%=f.submit class: "btn btn-success"%>
  <%end%>
</div>
<%end%>
</div>

app/views/admin/authors/edit.html.erb
<div class="row">
  <div class="jumbotron" style="text-align:center">
      <h2 style="letter-spacing:7px"><u>Edit Author Template</u></h2>
  </div>
</div>

<div class="row">
  <%=render "form"%>
</div>

app/views/admin/authors/index.html.erb
<%=link_to "Add New Author", new_admin_author_path%>

app/views/admin/authors/new.html.erb
<div class="row">
  <div class="jumbotron" style="text-align:center;">
      <h2 style="letter-spacing:7px;font-size:40px"><u>New Author Template</u></h2>
  </div>
</div>

<div class="row">
  <%@t = 1%>
  <%=render "form"%>
</div>