config/routes.rb
Rails.application.routes.draw do
	root 'catalogs#index'
 	
	get '/signup', to: 'users#new', as: 'signup'
	get '/signin', to: 'sessions#new', as: 'signin'
	post '/signin', to: 'sessions#create'
	get '/signout', to: 'sessions#destroy', as: 'signout'
	get 'reset_password', to: 'password_resets#new'
	get '/expired_token', to:'password_resets#expired_token'

	namespace :admin do
		get 'base/index'
		resources :authors
		resources :books
		resources :publishers
	end
	
	resources :users, only: [:index,:show, :new, :create, :destroy]
	resources :catalogs, only: [:index, :show] do
		collection do
			post :search, to: "catalogs#search"
		end
	end

	resources :carts,only: [:show, :destroy]
	resources :cart_items, only: [:create]
	resources :orders, only: [:new, :create]
	resources :password_resets, only: [:create,:edit,:update]
	

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user

  validates :addres_line1, :city, :state, :zipcode, presence: true
end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :publications, dependent: :destroy
	has_many :books, through: :publications

  validates :first_name, presence: true
  validates :second_name, presence: true

  def full_name
    "#{first_name} #{second_name}"
  end

  scope :recent, lambda {order("authors.created_at DESC")}
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :publisher
	has_many :publications, dependent: :destroy
	has_many :authors, through: :publications

	validates :title, presence: true
	validates :isbn, presence: true
	validates :description, presence: true
	validates :published_at, presence: true
	validates :publisher_id, presence: true
	validates :page_count, numericality: {only_integer: true, greater_than: 0}
	validates :price, numericality: {greater_than_or_equal_to: 0.0}

	scope :recent, lambda {order("books.created_at DESC")}

	mount_uploader :book_cover, BookCoverUploader

	def self.search_by_title(title)
		where('title LIKE ?', "%#{title}%").order(:title)
	end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :cart_items, dependent: :destroy
	has_many :books, through: :cart_items

		def add_book_to_cart_items(book_id)
			#require 'pry';binding.pry
			cart_item = cart_items.where(book_id: book_id).first

			# array of single item or nil

			if cart_item.nil?

				price = Book.find(book_id).price
				cart_item = cart_items.create(book_id: book_id, quantity: 1, price: price)
			else
				quantity = cart_items.quantity + 1
				cart_items.update(quantity: quantity)
				cart_item
			end
		end

		def total_sale
			#require 'pry';binding.pry
			cart_items.map {|item| item.line_total}.reduce(:+) || 0.0
		end

		def total_sale_in_cents
			(total_sale*100).to_i
		end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :book

  def line_total
  	price*quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items

	def order_total
		#require 'pry';binding.pry
		#order_items.map {|order_item| order_item.quantity*order_item.price}.reduce(:+)
				#OR
		order_items.to_a.inject(0.0) {|sum, order_item| sum+ order_item.quantity*order_item.price}
	end	
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :book

  def line_total
  	quantity*price
  end
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books

  validates :name, presence: true,
                   uniqueness: {case_sensitive: false}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :addresses
	has_many :orders
	before_create :generate_token
	has_secure_password

	accepts_nested_attributes_for :addresses

	regx = /\A[\w+\-.|\_]+@[a-z\d\-.]+\.[a-z]{2,4}\z/i
	validates :username, presence: true
	validates :email, presence: true, 
					  format: {with: regx},
					  uniqueness: true

	def self.authenticate(email, password)
		user = User.find_by(email: email)
		user && user.authenticate(password)
	end	

	def to_param
		token
	end

	

		def generate_token
			self.token = SecureRandom.urlsafe_base64
		end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :find_books, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.recent
  end

  def show
  end

  def new
    @book = Book.new
    @publishers = Publisher.all
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "Book has been created"
      redirect_to @book
    else
      flash[:danger] = "Book has not been created"
      @publishers = Publisher.all
      @authors = Author.all
      render :new
    end
  end

  def edit
    @publishers = Publisher.all
    @authors = Author.all
  end

  def update
    if @book.update(book_params)
      flash[:success] = "Book has been updated"
      redirect_to @book
    else
      flash[:danger] = "Book has not been updated"
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:success] = "Book has been deleted"
    redirect_to books_path
  end

  private

    def find_books
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:book_cover,:title, :isbn, :description, :published_at, :publisher_id, :page_count, :price,author_ids: [])
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :find_cart

  def show
  end

  def destroy
  	@cart.destroy
  	session[:cart_id] = nil
  	redirect_to catalogs_path
  end

  private

  	def find_cart
  		@cart = Cart.find(params[:id])
  	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :require_signin
	before_action :set_cart
  def new
  	@order = Order.new
  end
  def create
  	@order = current_user.orders.build
  	transfer_cart_items
  	if @order.valid?
  		total_sale = @cart.total_sale_in_cents
  		Stripe.api_key = ENV['STRIPE_SECRET_KEY']
  		token = params[:stripeToken] 
  		begin
  			charge = Stripe::Charge.create(amount: total_sale, currency: "usd", source: token)
  			@order.save
  			@cart.destroy
  			session[:cart_id] = nil
  			OrderMailer.notify_on_successful_order(current_user, @order).deliver_now
  			flash[:success] = "Order has been created" 	
  		rescue Stripe::CardError => e
  			flash[:danger] = "Order has not been created\n" + e.message  		 	
  		end 

  	end
  	redirect_to root_path
  end
  private
  	def transfer_cart_items
  		@cart.cart_items.each do |item|
  			@order.order_items << OrderItem.new(
  					book_id: item.book_id,
  					quantity: item.quantity,
  					price: item.price
  				)
  		end
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#sncd
	before_action :find_users, only: [:show, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
    @user.addresses.build
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User has been created"
      redirect_to signin_path
    else
      flash[:danger] = "User has not been created"
      render :new
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "User has been deleted"
    redirect_to root_path
  end

  private

    def find_users
      @user = User.find_by(token: params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, addresses_attributes: [:addres_line1, :address_line2, :city, :state, :zipcode])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/carts/_cart.html.erb
<div id="cart-items">
	<%=render cart.cart_items%>
</div>
<hr />
<div id="cart-total">
	<strong>Total:</strong> <%=number_to_currency(cart.total_sale) || number_to_currency(0)%>
</div>
<br>
<%=button_to "Checkout", new_order_path, method: :get, class: "btn btn-success", id: "checkout"%>
<br>
<hr/>
<%=button_to "Clear Cart", cart_path(cart), method: :delete, data: {confirm: "Are you sure to clear the cart"}, class: "btn btn-danger", id: "clearcart"%>
<%=javascript_tag do%>
	if($(location).attr('pathname') === '/orders/new'){
		$("#checkout,#clearcart").hide();
	}
	else{}
<%end%>

app/views/carts/show.html.erb
<section>
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<header>
				<h3 class="titles">
					Your Shopping Cart <%=image_tag 'cart.png'%>
				</h3>
			</header>

			<%@cart.cart_items.each do |item|%>
				<%=item.quantity%>&times;<%=item.book.title%> = <%="#{number_to_currency(item.line_total)}"%>
			<%end%>

			<hr />
			<br>
			<%=button_to "Checkout", new_order_path, method: :get, class: "btn btn-success", id: "checkout"%>
			<br>
			<hr/>
			<%=button_to "Clear Cart", cart_path(cart), method: :delete, data: {confirm: "Are you sure to clear the cart"}, class: "btn btn-danger", id: "clearcart"%>
		</div>
	</div>
</section>
<%=javascript_tag do%>
	if($(location).attr('pathname') === '/orders/new'){
		$("#checkout,#clearcart").hide();
	}
	else{}
<%end%>

app/views/orders/new.html.erb
<% content_for(:head) do %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>

  <script type="text/javascript">
 
  </script>

  <%= javascript_tag "Stripe.setPublishableKey('#{ENV['STRIPE_PUBLISHABLE_KEY']}');" %>
  <%= javascript_include_tag 'orders' %>
<% end %>

<div class='row'>
  <div class='col-md-10'>
    <%= bootstrap_form_for(@order, :html => {:class => "form-horizontal", id: "payment-form"}) do |f| %>
      <fieldset>
        <span class="order-errors"></span>
        <div class="form-group">
          <%= label_tag :credit_card_number, 'Credit Card Number', class: 'control-label col-sm-4' %>
          <div class="col-sm-6">
            <%= text_field_tag :credit_card_number, nil, name: nil, data: { stripe: 'number' }, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= label_tag :security_code, 'Security Code', class: 'control-label col-sm-4' %>
          <div class="col-sm-6">
            <%= text_field_tag :security_code, nil, name: nil, data: { stripe: 'cvc' }, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= label_tag nil, 'Expiration', class: 'control-label col-sm-4' %>
          <div class="col-sm-3">
            <%= select_month(Date.today, {add_month_numbers: true},  class: 'form-control', name: nil, data: {stripe: 'exp-month'}) %>
          </div>
          <div class="col-sm-3">
            <%= select_year(Date.today.year, {start_year: Date.today.year, end_year: Date.today.year + 4},  class: 'form-control', name: nil, data: {stripe: 'exp-year'}) %>
          </div>
        </div>
      </fieldset>
      <fieldset class="actions control-group col-sm-offset-4">
        <div class='controls'>
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="col-md-6 col-md-offset-3" style="text-align:center">
<%=bootstrap_form_for(@user, :html=> {class: 'form-horizontal'}) do |f| %>
	
	<div class="form-group">
		<%=f.text_field :username, hide_label: true, placeholder: "enter Username (ex: Bill123)", id: "userUsername", class: "form-control"%>
	</div>

	<div class="form-group">
		<%=f.email_field :email, hide_label: true, placeholder: "enter email (ex: bill@example.com)", id: "userEmail", class: "form-control"%>
	</div>

	<div class="form-group">
		<%=f.password_field :password, placeholder: "enter Password",class: "form-control", id: "userPassword"%>
	</div>

	<div class="form-group">
		<%=f.password_field :password_confirmation, placeholder: "Re-enter Password",class: "form-control", id: "userPasswordConfirmation"%>
	</div>
	<hr>
	<!-- ============== Nested Attributed for address ============== -->

		<%=f.fields_for :addresses do |address|%>

			<div class="form-group">
		<%=address.text_field :addres_line1, hide_label: true, placeholder: "enter Street Address (ex: 623 Eloisa Flat)", id: "addressAddress", class: "form-control"%>
			</div>

			<div class="form-group">
		<%=address.text_field :address_line2, hide_label: true, placeholder: " Second Line of Address (optional)", id: "addressAddress2", class: "form-control"%>
			</div>

			<div class="form-group">
		<%=address.text_field :city, hide_label: true, placeholder: "enter City (ex: South Dexterstad)", id: "addressCity", class: "form-control"%>
			</div>

			<div class="form-group">
		<%=address.text_field :state, hide_label: true, placeholder: "enter State (ex: Idaho)", id: "addressState", class: "form-control"%>
			</div>

			<div class="form-group">
		<%=address.text_field :zipcode, hide_label: true, placeholder: "enter Zipcode (ex: 25461 )", id: "addressZipcode", class: "form-control"%>
			</div>
		<%end%>

	<!-- ************************************************************ -->
		<hr>
	<div class="form-group actions control-group">
		<%=f.submit class: "btn btn-warning"%>
	</div>
<%end%>
<br/><br/>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= link_to user.email, user %><br>
<% end %>

app/views/users/new.html.erb
<div class="row" style="width:100vw">
  <div class="heading" style="text-align:center;">
      <h2 style="letter-spacing:7px;line-height: 1.6em;">Join Us<span class="glyphicon glyphicon-user"></span></h2>
  </div>
</div>

<div class="row" style="width:100vw">
  <%=render "form"%>
</div>

app/views/users/show.html.erb
<section>
	<div class='col-sm-10 col-sm-offset-1'>
		<header>
			<h2 class='titles'><%= "#{@user.username}" %>'s Profile</h2>
		</header>
		<h3 id="email">Email: <%= @user.email %></h3>
	</div>
</section>
<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>