config/routes.rb
Rails.application.routes.draw do
	root 'catalogs#index'
 	
	get '/signup', to: 'users#new', as: 'signup'
	get '/signin', to: 'sessions#new', as: 'signin'
	post '/signin', to: 'sessions#create'
	get '/signout', to: 'sessions#destroy', as: 'signout'
	get 'reset_password', to: 'password_resets#new'
	get '/expired_token', to:'password_resets#expired_token'

	namespace :admin do
		get 'base/index'
		resources :authors
		resources :books
		resources :publishers
	end
	
	resources :users, only: [:index,:show, :new, :create, :destroy]
	resources :catalogs, only: [:index, :show] do
		collection do
			post :search, to: "catalogs#search"
		end
	end

	resources :carts,only: [:show, :destroy]
	resources :cart_items, only: [:create]
	resources :orders, only: [:new, :create]
	resources :password_resets, only: [:create,:edit,:update]
	

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user

  validates :addres_line1, :city, :state, :zipcode, presence: true
end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :publications, dependent: :destroy
	has_many :books, through: :publications

  validates :first_name, presence: true
  validates :second_name, presence: true

  def full_name
    "#{first_name} #{second_name}"
  end

  scope :recent, lambda {order("authors.created_at DESC")}
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :publisher
	has_many :publications, dependent: :destroy
	has_many :authors, through: :publications

	validates :title, presence: true
	validates :isbn, presence: true
	validates :description, presence: true
	validates :published_at, presence: true
	validates :publisher_id, presence: true
	validates :page_count, numericality: {only_integer: true, greater_than: 0}
	validates :price, numericality: {greater_than_or_equal_to: 0.0}

	scope :recent, lambda {order("books.created_at DESC")}

	mount_uploader :book_cover, BookCoverUploader

	def self.search_by_title(title)
		where('title LIKE ?', "%#{title}%").order(:title)
	end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :cart_items, dependent: :destroy
	has_many :books, through: :cart_items

		def add_book_to_cart_items(book_id)
			#require 'pry';binding.pry
			cart_item = cart_items.where(book_id: book_id).first

			# array of single item or nil

			if cart_item.nil?

				price = Book.find(book_id).price
				cart_item = cart_items.create(book_id: book_id, quantity: 1, price: price)
			else
				quantity = cart_items.quantity + 1
				cart_items.update(quantity: quantity)
				cart_item
			end
		end

		def total_sale
			#require 'pry';binding.pry
			cart_items.map {|item| item.line_total}.reduce(:+) || 0.0
		end

		def total_sale_in_cents
			(total_sale*100).to_i
		end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :book

  def line_total
  	price*quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items

	def order_total
		#require 'pry';binding.pry
		#order_items.map {|order_item| order_item.quantity*order_item.price}.reduce(:+)
				#OR
		order_items.to_a.inject(0.0) {|sum, order_item| sum+ order_item.quantity*order_item.price}
	end	
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :book

  def line_total
  	quantity*price
  end
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books

  validates :name, presence: true,
                   uniqueness: {case_sensitive: false}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :addresses
	has_many :orders
	before_create :generate_token
	has_secure_password

	accepts_nested_attributes_for :addresses

	regx = /\A[\w+\-.|\_]+@[a-z\d\-.]+\.[a-z]{2,4}\z/i
	validates :username, presence: true
	validates :email, presence: true, 
					  format: {with: regx},
					  uniqueness: true

	def self.authenticate(email, password)
		user = User.find_by(email: email)
		user && user.authenticate(password)
	end	

	def to_param
		token
	end

	

		def generate_token
			self.token = SecureRandom.urlsafe_base64
		end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :find_books, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.recent
  end

  def show
  end

  def new
    @book = Book.new
    @publishers = Publisher.all
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "Book has been created"
      redirect_to @book
    else
      flash[:danger] = "Book has not been created"
      @publishers = Publisher.all
      @authors = Author.all
      render :new
    end
  end

  def edit
    @publishers = Publisher.all
    @authors = Author.all
  end

  def update
    if @book.update(book_params)
      flash[:success] = "Book has been updated"
      redirect_to @book
    else
      flash[:danger] = "Book has not been updated"
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:success] = "Book has been deleted"
    redirect_to books_path
  end

  private

    def find_books
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:book_cover,:title, :isbn, :description, :published_at, :publisher_id, :page_count, :price,author_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/index.html.erb
index.html.erb

app/views/layouts/_head.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" style="font-size:30px;letter-spacing:7px;color:#CCCCFF;">Sasti Books</a><%=image_tag 'logo.svg',id: "logo"%>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li id="li1" class="active"><%=link_to "Home", root_path%></li>
        <%if current_user && current_user.admin?%>
        <li id="li2"><%=link_to "Authors",admin_authors_path%></li>
        <li id="li3"><%=link_to "Books", admin_books_path%></li>
         <li id="li4"><%=link_to "Publishers", admin_publishers_path%></li>
        <li id="li5"><%=link_to "Users", users_path%></li>
        <%end%>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%if session[:user_id]%>
        <li><a href="/signout"><span class="glyphicon glyphicon-log-out"></span> Sign Out</a></li>
        <%else%>
        <li><a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="/signin"><span class="glyphicon glyphicon-log-in"></span> Sign In</a></li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_search.html.erb
<div class="row" style="width:100vw">
	<div class="col-md-12">
		<div class="well" style="text-align:center;margin-left:1%;padding:5px;">
			<%=form_tag (search_catalogs_path) do%>
				<%=text_field_tag :search_word, nil, placeholder: " Searh for Book", id: "search_field"%>
				<%=submit_tag "Search Book", class: "btn btn-default"%>	
			<%end%>
		</div>
	</div>	
</div>

app/views/layouts/application.html.erb
auto<!DOCTYPE html>
<html>
<head>
  <title>BookApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--link href='https://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'-->
  <%= yield :head %>
</head>
<body>
<%=render 'layouts/head'%>
<%=render 'layouts/search'%>
<%if flash[:success]%>
<div id="fflash" class="a-s" style="position:absolute;margin-top:20px;height:auto;width:500px;left:50%;margin-left:-250px;text-align:center;">
<%else%>
<div id="fflash" class="a-d" style="position:absolute;margin-top:20px;height:auto;width:500px;left:50%;margin-left:-250px;text-align:center;">
<%end%>
  <%flash.each do |name,msg|%>
    <div id="k" class="alert alert-<%='#{name}'%>">
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%=content_tag :div, msg, id: "flash_#{name}"if msg.is_a?(String)%>
    </div>
  <%end%>
  <%if flash%>
      <%=javascript_tag do%>
          setTimeout(function(){
            $('#fflash').fadeOut(400);
            
          },4000);
      <%end%>
  <%end%>
</div>
<!--=================== YIELD ==================== -->
<%= yield %>
<!--============================================== -->
<%if request.fullpath == root_path%>
  <!-- nothing -->
<%else%>
  <div id="side_cart" class=""><h2>Your Cart</h2>
  <div id="cartUp"><%=render @cart if @cart%></div>
  </div>
<%end%>  
<style type="text/css">
<%if flash[:success] ||flash[:danger]%>
.a-s{background-color: rgb(58,193,98) !important;color:#fff;}
.a-d{background-color: #ff6666 !important;color:#fff;}
<%end%>
</style>

<%=javascript_tag do%>
$('#k').click(function(){
  $('#fflash').fadeOut(450);
});
<%end%>

</body>
</html>